maple/tag/urls.py
from flask import Blueprint
from .views import tag, rss

site = Blueprint('tag', __name__)

site.add_url_rule('', view_func=tag, defaults={'tag': None})
site.add_url_rule('/<tag>', view_func=tag)
site.add_url_rule('/<tag>/feed', view_func=rss)

maple/urls.py
from maple.forums.urls import site as forums_site
from maple.topic.urls import site as topic_site
from maple.board.urls import site as board_site
from maple.user.urls import site as user_site
from maple.mine.urls import site as mine_site
from maple.setting.urls import site as setting_site
from maple.upload.urls import site as upload_site
from maple.tag.urls import site as tag_site
from maple.docs.views import site as docs_site


def register_urls(app):
    app.register_blueprint(forums_site)
    app.register_blueprint(board_site, url_prefix='/<parent_b>')
    app.register_blueprint(tag_site, url_prefix='/t')
    app.register_blueprint(topic_site, url_prefix='/topic')
    app.register_blueprint(mine_site, url_prefix='/user')
    app.register_blueprint(user_site, url_prefix='/u/<user_url>')
    app.register_blueprint(setting_site, url_prefix='/setting')
    app.register_blueprint(upload_site)
    app.register_blueprint(docs_site, subdomain='docs')
    from maple.auth import views
    from maple.admin import admin

maple/tag/models.py
from maple import db
from datetime import datetime

tag_topic = db.Table('tag_topic', db.Column('tags_id', db.Integer,
                                            db.ForeignKey('tags.id')),
                     db.Column('topics_id', db.Integer,
                               db.ForeignKey('topics.id')))

tags_parents = db.Table(
    'tags_parents', db.Column('tag_id', db.Integer, db.ForeignKey('tags.id')),
    db.Column('parent_id', db.Integer, db.ForeignKey('tags.id')))


class Tags(db.Model):
    __tablename__ = 'tags'
    id = db.Column(db.Integer, primary_key=True)
    time = db.Column(db.DateTime, default=datetime.utcnow())
    tagname = db.Column(db.String(64), nullable=False)
    summary = db.Column(db.Text)
    tags = db.relationship('Topic',
                           secondary=tag_topic,
                           lazy='dynamic',
                           backref="tags")
    parents = db.relationship(
        'Tags',
        secondary=tags_parents,
        primaryjoin=(id == tags_parents.c.tag_id),
        secondaryjoin=(id == tags_parents.c.parent_id),
        backref=db.backref('children', lazy='joined'))

    def __str__(self):
        return self.tagname

    def __repr__(self):
        return '<Tags %r>' % self.tagname

maple/tag/views.py
from flask import render_template, request, url_for
from maple import app
from maple.helpers import is_num
from maple.topic.models import Topic
from maple.filters import Filters
from .models import Tags
from urllib.parse import urljoin
from werkzeug.utils import escape
from werkzeug.contrib.atom import AtomFeed


def tag(tag):
    print(url_for('.tag'))
    if tag is None:
        tags = Tags.query.distinct(Tags.tagname).all()
        data = {'title': '所有标签 - ', 'tags': tags}
        return render_template('tag/tag_list.html', **data)
    else:
        page = is_num(request.args.get('page'))
        topic_base = Topic.query.join(Topic.tags).filter(Tags.tagname == tag)
        topics = topic_base.filter(Topic.is_top == False).paginate(
            page, app.config['PER_PAGE'],
            error_out=True)
        top_topics = topic_base.filter(Topic.is_top == True).limit(5).all()
        tag = Tags.query.filter_by(tagname=tag).first_or_404()
        data = {'title': '%s - ' % tag,
                'tag': tag,
                'topics': topics,
                'top_topics': top_topics}
        return render_template('tag/tag.html', **data)

# @site.route('/hot')
# def hot():
#     tags = Tags.query.order_by(Tags.time.desc()).limit(10).all()
#     return tags

# @site.route('/recent')
# def recent():
#     tags = Tags.query.order_by(Tags.time.desc()).limit(10).all()
#     return tags


def rss(tag):
    feed = AtomFeed('%s·HonMaple社区' % tag,
                    feed_url=request.url,
                    url=request.url_root,
                    subtitle='I like solitude, yearning for freedom')
    topics = Topic.query.join(Topic.tags).filter(Tags.tagname == tag).limit(
        10).all()
    for topic in topics:
        feed.add(
            topic.title,
            escape(Filters.safe_markdown(topic.content) if topic.is_markdown
                   else topic.content),
            content_type='html',
            author=topic.author.username,
            url=urljoin(request.url_root,
                        url_for('topic.topic', topicId=topic.uid)),
            updated=topic.publish,
            published=topic.publish)
    return feed.get_response()

templates/tag/panel.html
{% from 'base/panel.html' import base %}
{% from 'base/panel.html' import count %}
{% macro tag_list() -%}
{{ base() }}
{%- endmacro %}

{% macro tag(tag) -%}
{{ base() }}
<div class="panel panel-default hidden-xs" style="font-size:13px;">
    {{ parents(tag) }}
    {{ children(tag) }}
</div>
{{ count() }}
{%- endmacro %}

{% macro parents(tag) -%}
<div class="panel-body" style="padding:10;margin:0;">
    <strong>父节点</strong>
</div>
{% if tag.parents -%}
{% for parent in tag.parents -%}
{{ link(parent.tagname) }}
{%- endfor %}
<div style="border-bottom:1px solid #eee"></div>
{{ relation(tag) }}
{% else %}
{{ link('honmaple') }}
{%- endif %}
<div style="border-bottom:1px solid #eee"></div>
{%- endmacro %}

{% macro children(tag) -%}
{% if tag.children -%}
<div class="panel-body" style="padding:10;margin:0;">
    <strong>子节点</strong>
</div>
{% for child in tag.children -%}
{{ link(child.tagname) }}
{%- endfor %}
{%- endif %}
{%- endmacro %}

{% macro relation(tag) -%}
{% set parent = tag.parents[0] %}
{% if parent.children -%}
<div class="panel-body" style="padding:10;margin:0;">
    <strong>相关节点</strong>
</div>
{% for child in parent.children if child.tagname != tag.tagname -%}
{{ link(child.tagname) }}
{%- endfor %}
{%- endif %}
{%- endmacro %}

{% macro link(name) -%}
<div class="panel-body" style="padding:10px;margin-top:0;padding-top:0">
    <img alt="" src="{{ url_for('avatar',text=name)}}" style="width:24px;"/>
    <a class="text-capitalize" href="{{ url_for('tag.tag',tag=name)}}" style="color:#555;">{{ name }}</a>
</div>
{%- endmacro %}

templates/tag/tag.html
{% extends 'base/base.html' %}
{% block script %}
<script type="text/javascript" charset="utf-8">
 var sortData = {
     "type" : 'tags',
     "page" : '{{ topics.page }}',
     "uid" : "{{ tag.tagname }}"};
</script>
{{ super()}}
{% endblock %}
{% block content %}
{{ breadcrumb(hrefs={_('All Tags'):url_for('tag.tag')},active=tag.tagname)}}
<div class="row">
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-body" style="border-bottom: 1px solid #ddd;">
                <div class="media">
                    <div class="media-left">
                        <a href="{{ request.path }}">
                            <img class="media-object img-circle" src="{{ url_for('avatar',text=tag.tagname)}}" alt="avatar" style="width:56px;height:56px">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading"><strong class="text-capitalize">{{ tag.tagname }}</strong></h4>
                        {% set summary = tag.summary %}
                        {% if summary -%}
                        {{ summary }}
                        {%- endif %}
                    </div>
                    <div class="media-right">
                        <span class="rss">
                            <a href="{{ url_for('tag.rss',tag=tag.tagname)}}">
                                <i class="icon-rss" style="padding:2px;white-space:nowrap;">Rss</i>
                            </a>
                        </span>
                        {% if g.user.is_authenticated %}
                        {% if current_user in tag.followers %}
                        <button class="btn btn-sm btn-default tagfollow active" id="{{ tag.id}}" style="padding:0 5px">取消关注</button>
                        {% else %}
                        <button class="btn btn-sm btn-default tagfollow" id="{{ tag.id}}" style="padding:0 5px">关注</button>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
            {% from 'topic/topic_list.html' import view as board_view %}
            {{ board_view(topics,top_topics)}}
            {{ p_footer(topics, 'tag.tag',kw=dict(tag=tag.tagname))}}
        </div>
    </div>
    <div class="col-md-3" style="padding-left:0">
        {% from 'tag/panel.html' import tag as tag_panel %}
        {{ tag_panel(tag) }}
    </div>
</div>
{% endblock %}

templates/tag/tag_list.html
{% extends 'base/base.html' %}
{% import 'base/link.html' as link_base %}
{% block content %}
{{ breadcrumb(active=_('All Tags'))}}
<div class="row">
    <div class="col-md-9">
        <div class="panel panel-primary">
            <div class="panel-heading">
                {{_('All Tags')}}
            </div>
            {% if tags %}
            <div class="panel-body">
                {% for tag in tags %}
                {{ link_base.tag(tag) }}
                {% endfor %}
            </div>
            {% else %}
            <div class="panel-body text-center">
                {{_('No Tag')}}
                暂无标签
            </div>
            {% endif %}
        </div>
    </div>
    <div class="col-md-3" style="padding-left:0">
        {{ panel_base.tag_list() }}
    </div>
</div>
{% endblock %}