maple/topic/urls.py
from flask import Blueprint
from .views import ask, good, preview, vote_up, vote_down, edit
from .views import TopicAPI, ReplyAPI

site = Blueprint('topic', __name__)

site.add_url_rule('/ask', view_func=ask)
site.add_url_rule('/good', view_func=good)
site.add_url_rule('/preview', view_func=preview, methods=['POST'])
site.add_url_rule('/up/<topicId>', view_func=vote_up, methods=['POST'])
site.add_url_rule('/down/<topicId>', view_func=vote_down, methods=['POST'])
site.add_url_rule('/edit/<topicId>', view_func=edit)

topic_view = TopicAPI.as_view('topic')
# /topic
# /topic         post
# /topic/<uid>   get,put,delete
site.add_url_rule('',
                  defaults={'topicId': None},
                  view_func=topic_view,
                  methods=['GET'])
site.add_url_rule('', view_func=TopicAPI.as_view('post'), methods=['POST'])
site.add_url_rule('/<topicId>',
                  view_func=topic_view,
                  methods=['GET', 'PUT', 'DELETE'])

reply_view = ReplyAPI.as_view('reply')
site.add_url_rule('reply/<topicId>', view_func=reply_view, methods=['POST'])

maple/urls.py
from maple.forums.urls import site as forums_site
from maple.topic.urls import site as topic_site
from maple.board.urls import site as board_site
from maple.user.urls import site as user_site
from maple.mine.urls import site as mine_site
from maple.setting.urls import site as setting_site
from maple.upload.urls import site as upload_site
from maple.tag.urls import site as tag_site
from maple.docs.views import site as docs_site


def register_urls(app):
    app.register_blueprint(forums_site)
    app.register_blueprint(board_site, url_prefix='/<parent_b>')
    app.register_blueprint(tag_site, url_prefix='/t')
    app.register_blueprint(topic_site, url_prefix='/topic')
    app.register_blueprint(mine_site, url_prefix='/user')
    app.register_blueprint(user_site, url_prefix='/u/<user_url>')
    app.register_blueprint(setting_site, url_prefix='/setting')
    app.register_blueprint(upload_site)
    app.register_blueprint(docs_site, subdomain='docs')
    from maple.auth import views
    from maple.admin import admin

maple/topic/models.py
from flask import current_app
from maple import db
from datetime import datetime
from sqlalchemy import event


class Topic(db.Model):
    __tablename__ = 'topics'
    id = db.Column(db.Integer, primary_key=True)
    uid = db.Column(db.String(36), nullable=False)
    title = db.Column(db.String(81), nullable=False)
    content = db.Column(db.Text, nullable=False)
    publish = db.Column(db.DateTime, default=datetime.utcnow())
    updated = db.Column(db.DateTime)
    vote = db.Column(db.Integer, default=0)

    author_id = db.Column(db.Integer,
                          db.ForeignKey('users.id',
                                        ondelete="CASCADE"))
    author = db.relationship('User',
                             backref=db.backref('topics',
                                                cascade='all,delete-orphan',
                                                lazy='dynamic'))
    board_id = db.Column(db.Integer,
                         db.ForeignKey('boards.id',
                                       ondelete="CASCADE"))
    board = db.relationship(
        'Board',
        backref=db.backref('topics',
                           cascade='all,delete-orphan',
                           lazy='dynamic',
                           order_by='Topic.publish.desc()'))

    is_good = db.Column(db.Boolean, default=False)
    is_top = db.Column(db.Boolean, default=False)
    # is_top = db.Column(db.Integer, default = 0)
    is_markdown = db.Column(db.Boolean, default=False)
    is_draft = db.Column(db.Boolean, default=False)

    __mapper_args__ = {"order_by": publish.desc()}

    def __str__(self):
        return self.title

    def __repr__(self):
        return "<Topic %r>" % self.title

    def pagea(self, page=None):
        per_page = current_app.config['PER_PAGE']
        return self.paginate(page, per_page, True)

    # @staticmethod
    # def page(page):
    #     app = current_app._get_current_object()
    #     per_page = app.config['PER_PAGE']
    #     return Topic.paginate(page, per_page, True)
    def to_json(self):
        data = {
            'id': self.id,
            'uid': self.uid,
            'title': self.uid,
            'tags': self.tags,
            'content': self.content,
            'is_good': self.is_good,
            'is_markdown': self.is_markdown,
            'is_top': self.is_top,
            'publish': self.publish,
            'author':self.author.username
        }


@event.listens_for(Topic, 'before_update')
def receive_after_update(mapper, connection, target):
    target.updated = datetime.now()


class Reply(db.Model):
    __tablename__ = 'replies'
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text, nullable=False)
    # quote = db.Column(db.Text, nullable=True)
    publish = db.Column(db.DateTime, default=datetime.now())
    updated = db.Column(db.DateTime)
    topic_id = db.Column(db.Integer,
                         db.ForeignKey('topics.id',
                                       ondelete="CASCADE"))
    topic = db.relationship(
        'Topic',
        backref=db.backref('replies',
                           cascade='all,delete-orphan',
                           lazy='dynamic',
                           order_by='Reply.publish.desc()'))

    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    author = db.relationship('User',
                             backref=db.backref('replies',
                                                lazy='dynamic',
                                                order_by='Reply.publish'))
    likers = db.relationship(
        'User',
        secondary='likes',
        backref=db.backref("likes", lazy='dynamic'))
    __mapper_args__ = {"order_by": publish.desc()}


class CollectTopic(db.Model):
    __tablename__ = 'collect_topic'
    id = db.Column(db.Integer, primary_key=True)
    topic_id = db.Column(db.Integer, db.ForeignKey('topics.id'))
    collect_id = db.Column(db.Integer, db.ForeignKey('collects.id'))


class Collect(db.Model):
    __tablename__ = 'collects'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32), nullable=False)
    description = db.Column(db.String(256))
    is_privacy = db.Column(db.Boolean, default=False)
    author_id = db.Column(db.Integer,
                          db.ForeignKey('users.id',
                                        ondelete="CASCADE"))
    author = db.relationship('User',
                             backref=db.backref('collects',
                                                cascade='all,delete-orphan',
                                                lazy='dynamic'))

    topics = db.relationship('Topic',
                             secondary='collect_topic',
                             lazy='dynamic',
                             backref="collects")

    def __str__(self):
        return self.name

    def __repr__(self):
        return "<Collect %r>" % self.name


class Like(db.Model):
    __tablename__ = 'likes'
    id = db.Column(db.Integer, primary_key=True)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    reply_id = db.Column(db.Integer, db.ForeignKey('replies.id'))
    like_time = db.Column(db.DateTime, default=datetime.now())

maple/topic/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Length
from flask_babelex import lazy_gettext as _
from maple.forums.models import Board


class TopicForm(Form):
    title = StringField(_('Title:'), [DataRequired(), Length(min=4, max=36)])
    content = TextAreaField(_('Content:'), [DataRequired(), Length(min=6)])
    category = SelectField(
        _('Category:'),
        choices=[(b.id, b.board + '   --' + b.parent_board)
                 for b in Board.query.all()],
        coerce=int)
    tags = StringField(_('Tags:'), [DataRequired(), Length(min=2, max=36)])
    choice = SelectField('choice',
                         choices=[(1, 'Markdown'), (2, 'Default')],
                         coerce=int)


class ReplyForm(Form):
    content = TextAreaField(_('Content:'), [DataRequired()])

maple/topic/views.py
from flask import (render_template, redirect, url_for, request, jsonify,
                   current_app)
from flask.views import MethodView
from flask_login import login_required
from flask_maple.forms import flash_errors, return_errors
from flask_babelex import gettext as _
from maple import db
from maple.helpers import replies_page
from maple.helpers import is_num
from maple.forums.models import Board
from maple.filters import safe_clean, Filters
from .models import Topic
from .forms import TopicForm, ReplyForm
from .controls import TopicModel, ReplyModel, vote
from .permission import (topic_permission, reply_permission, ask_permission,
                         vote_permission, preview_permission, edit_permission)


@login_required
@ask_permission
def ask():
    form = TopicForm()
    boardId = request.args.get('boardId')
    if boardId is not None:
        board = Board.query.filter_by(id=boardId).first()
        form.category.data = board.id

    data = {'title': '提问 - ', 'form': form}
    return render_template('topic/ask.html', **data)


@login_required
@edit_permission
def edit(topicId):
    topic = Topic.query.filter_by(uid=topicId).first_or_404()
    form = TopicForm()
    form.title.data = topic.title
    form.category.data = topic.board_id
    form.tags.data = ','.join([tag.tagname for tag in topic.tags])
    form.content.data = topic.content
    data = {'title': _('Edit -'), 'form': form, 'topic': topic}
    return render_template('topic/edit.html', **data)


def good():
    page = is_num(request.args.get('page'))
    topics = Topic.query.filter_by(is_good=True).paginate(
        page, current_app.config['PER_PAGE'],
        error_out=True)
    data = {'title': '精华文章 - ', 'topics': topics}
    return render_template('topic/topic_good.html', **data)


@login_required
@preview_permission
def preview():
    choice = request.values.get('choice')
    content = request.values.get('content')
    print(choice)
    if choice == '2':
        return safe_clean(content)
    else:
        return Filters.safe_markdown(content)


@vote_permission
def vote_up(topicId):
    topic = Topic.query.filter_by(uid=topicId).first_or_404()
    if not topic.vote:
        topic.vote = 1
    else:
        topic.vote += 1
    db.session.commit()
    html = vote(topic.vote)
    return jsonify(judge=True, html=html)


@vote_permission
def vote_down(topicId):
    topic = Topic.query.filter_by(uid=topicId).first_or_404()
    if not topic.vote:
        topic.vote = -1
    else:
        topic.vote -= 1
    db.session.commit()
    html = vote(topic.vote)
    return jsonify(judge=True, html=html)


class TopicAPI(MethodView):
    decorators = [topic_permission]

    def template_with_uid(self, data):
        return render_template('topic/content.html', **data)

    def template_without_uid(self, data):
        return render_template('topic/topic.html', **data)

    def get(self, topicId):
        page = is_num(request.args.get('page'))
        order = request.args.get('orderby')
        if topicId is None:
            topics, top_topics = TopicModel.get_list(page)
            data = {'title': '所有主题 - ',
                    'topics': topics,
                    'top_topics': top_topics}
            return self.template_without_uid(data)
        else:
            form = ReplyForm()
            topic, replies = TopicModel.get_detail(page, topicId, order)
            data = {'title': '%s - ' % topic.title,
                    'form': form,
                    'topic': topic,
                    'replies': replies}
            return self.template_with_uid(data)

    def post(self):
        form = TopicForm()
        if form.validate_on_submit():
            topic = TopicModel.post(form)
            return redirect(url_for('topic.topic', topicId=topic.uid))
        else:
            if form.errors:
                flash_errors(form)
            return redirect(url_for('topic.ask'))

    def put(self, topicId):
        form = TopicForm()
        if form.validate_on_submit():
            TopicModel.put(form, topicId)
            return jsonify(judge=True)
        else:
            if form.errors:
                return_errors(form)
            return redirect(url_for('topic.ask'))

    def delete(self, topicId):
        return 'delete'


class ReplyAPI(MethodView):
    decorators = [reply_permission]

    def post(self, topicId):
        form = ReplyForm()
        topic = Topic.query.filter_by(id=topicId).first_or_404()
        if form.validate_on_submit():
            rep = ReplyModel()
            reply = rep.post(form, topicId)
            page = replies_page(topic.id)
            return redirect(url_for('topic.topic',
                                    topicId=topic.uid,
                                    page=page,
                                    _anchor='reply' + str(reply.id)))
        else:
            if form.errors:
                flash_errors(form)
            page = replies_page(topic.id)
            return redirect(url_for('topic.topic',
                                    topicId=topic.uid,
                                    page=page,
                                    _anchor='content'))

    # def put(self, uid):
    #     return 'put'

    # def delete(self, uid):
    #     return 'delete'

maple/user/views.py
from flask import (render_template, request, g, url_for, redirect, abort,
                   current_app)
from flask_login import current_user
from maple.helpers import is_num
from maple.topic.models import Topic, Reply, Collect, Like
from maple.user.models import User
from sqlalchemy.sql import func


def user():
    topics = Topic.query.join(Topic.author).filter(
        User.username == g.user_url).paginate(1,
                                              current_app.config['PER_PAGE'],
                                              error_out=True)
    data = {'type': 'topic', 'topics': topics}
    return render_template('user/user.html', **data)


def topic():
    orderby = request.args.get('orderby')
    page = is_num(request.args.get('page'))
    all_order = ['vote', 'publish']
    if orderby and orderby not in all_order:
        abort(404)
    if orderby == 'vote':
        topics = Topic.query.join(Topic.author).filter(
            User.username == g.user_url).order_by(Topic.vote.desc()).paginate(
                page, current_app.config['PER_PAGE'],
                error_out=True)
    else:
        topics = Topic.query.join(Topic.author).filter(
            User.username == g.user_url).paginate(
                page, current_app.config['PER_PAGE'],
                error_out=True)
    data = {'type': 'topic', 'topics': topics}
    return render_template('user/user.html', **data)


def reply():
    order = request.args.get('orderby')
    page = is_num(request.args.get('page'))
    all_order = ['like', 'publish']
    if order and order not in all_order:
        abort(404)
    if order == 'like':
        user = User.query.filter_by(username=g.user_url).first_or_404()
        replies = Reply.query.outerjoin(Like).filter(
            Reply.author_id == user.id).group_by(Reply.id).order_by(func.count(
                Like.id).desc()).paginate(page, current_app.config['PER_PAGE'],
                                          True)
    else:
        replies = Reply.query.join(Reply.author).filter(
            User.username == g.user_url).paginate(
                page, current_app.config['PER_PAGE'],
                error_out=True)
    data = {'type': 'reply', 'replies': replies}
    return render_template('user/user.html', **data)


def collect():
    page = is_num(request.args.get('page'))
    per_page = current_app.config['PER_PAGE']
    if current_user.is_authenticated and current_user.username == g.user_url:
        collects = current_user.collects.paginate(
            page, per_page, error_out=True)
    else:
        collects = Collect.query.join(Collect.author).filter(
            Collect.is_privacy == False, User.username == g.user_url).paginate(
                page, per_page, error_out=True)
    data = {'type': 'collect', 'collects': collects}
    return render_template('user/user.html', **data)


def collect_detail(collectId):
    page = is_num(request.args.get('page'))
    per_page = current_app.config['PER_PAGE']
    if current_user.is_authenticated:
        collect = Collect.query.join(Collect.author).filter(
            Collect.id == collectId,
            User.username == g.user_url).first_or_404()
    else:
        collect = Collect.query.join(Collect.author).filter(
            Collect.id == collectId, Collect.is_privacy == False,
            User.username == g.user_url).first_or_404()
    topics = collect.topics.paginate(page, per_page, True)
    data = {'type': 'collect_detail', 'topics': topics, 'collect': collect}
    return render_template('user/user.html', **data)


def following():
    return redirect(url_for('mine.follow'))


def follower():
    page = is_num(request.args.get('page'))
    order = request.args.get('orderby')
    order_list = ['publish', 'score']
    if order and order not in order_list:
        abort(404)
    user = User.query.filter_by(username=g.user_url).first_or_404()
    followers = user.followers.paginate(page,
                                        current_app.config['PER_PAGE'],
                                        error_out=True)
    data = {'type': 'follower', 'followers': followers}
    return render_template('user/user.html', **data)

templates/topic/ask.html
{% extends 'base/base.html' %}
{% block script -%}
{{ super() }}
<script type="text/javascript">
 AskTopic("{{ url_for('topic.preview') }}")
</script>
{%- endblock script %}
{% block content %}
<style>
 .tokenfield .token {
     border: 1px solid #5cb85c;
     background-color: #5cb85c;
     color:#eee;
 }
</style>
{{ breadcrumb(active=_('Ask'))}}
<div class="panel panel-primary">
    <div class="panel-heading">{{ _('Ask') }}</div>
    <div class="panel-body" style="border-bottom:1px solid #f6e1e1;padding:10px 0;">
        <div class="row" style="margin:0;padding:0;">
            <form action="{{ url_for('topic.post') }}" method="POST">
                {% from 'topic/_form.html' import ask %}
                {{ ask(form) }}
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/topic/content.html
{% extends 'base/base.html' %}
{% block script -%}
{{ super() }}
<script type="text/javascript">
 var voteData = {
     'vote_up': "{{ url_for('topic.vote_up',topicId=topic.uid)}}",
     'vote_down': "{{ url_for('topic.vote_down',topicId=topic.uid)}}"
 };
 DoVote(voteData);
</script>
{%- endblock script %}

{% block content %}
{% set board = topic.board %}
<ol class="breadcrumb" style="margin:0">
    <li><a href="{{ url_for('forums.forums') }}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>{{ _('Index') }}</a></li>
    <li><a href="{{ url_for('board.board',parent_b=board.parent_board) }}">{{ board.parent_board }}</a></li>
    <li><a href="{{ url_for('board.board',parent_b=board.parent_board,child_b=board.board)}}">{{ board.board }}</a></li>
    <li class="active">{{ topic.title }}</li>
</ol>
{% from 'base/paginate.html' import footer as p_footer %}
<div class="row">
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading media ">
                <div class="media-body">
                    <h3 class="media-heading" style="font-size:20px;"><b>{{ topic.title}}</b></h3>
                    <small style="color:#999">
                        {{ votes(topic) }}
                        {% for tag in topic.tags %}
                        {{ link_base.tag(tag) }}
                        {% endfor %}
                        <span style="margin-left:10px;">
                            {% set last_reply = topic.replies.first() %}
                            {{ link_base.user(topic.author.username )}}
                            {{ _('published at %(time)s',time = topic.publish | timesince ) }}
                            {% if last_reply %}
                            · {{ _('The last reply published by %(author)s at %(time)s',author=link_base.user(last_reply.author.username),time=last_reply.publish | timesince)}}
                            {% endif %}
                        </span>
                    </small>
                </div>
                <div class="media-right">
                    <a href="{{ url_for('user.user',user_url=topic.author.username)}}">
                        <img class="media-object img-circle" src="{{ link_base.avatar(topic.author) }}" alt="avatar" style="width:64px;height:64px">
                    </a>
                </div>
            </div>
            <div class="panel-body topic-content">
                {% if topic.is_markdown %}
                {{ topic.content | markdown }}
                {% else %}
                {{ topic.content | safe_clean }}
                {% endif %}
            </div>
        </div>
        {% include 'topic/replies.html' %}
    </div>
    <div class="col-md-3" style="padding-left:0">
        {% set ask_url = url_for('topic.ask',boardId=topic.board.id) %}
        {% include 'topic/panel.html' %}
        {{ panel_base.board() }}
    </div>
</div>
{% endblock %}

{% macro votes(topic) -%}
<div class="votes">
    {% if topic.vote and topic.vote > 0 -%}
    {{ vote_a('up',topic.vote) }}
    {% else %}
    {{ vote_a('up') }}
    {%- endif %}
    {% if topic.vote and topic.vote < 0 %}
    {{ vote_a('down',topic.vote) }}
    {% else %}
    {{ vote_a('down') }}
    {%- endif %}
</div>
{%- endmacro %}

{% macro vote_a(vo,count=None) -%}
{% if count -%}
<a id="topic-{{ vo }}-vote" class="vote" href="javascript:void(0)" style="text-decoration:none;">
    <i class="icon-chevron-{{ vo }}">{{ count }}</i>
</a>
{% else %}
<a id="topic-{{ vo }}-vote" class="vote" href="javascript:void(0)" style="text-decoration:none;">
    <i class="icon-chevron-{{ vo }}"></i>
</a>
{%- endif %}
{%- endmacro %}

templates/topic/edit.html
{% extends 'base/base.html' %}
{% block script -%}
{{ super() }}
<script type="text/javascript">
 EditTopic("{{ url_for('topic.preview') }}","{{ url_for('topic.topic',topicId=topic.uid) }}")
</script>
{%- endblock script %}
{% block content %}
{{ breadcrumb(active='编辑')}}
<style>
 .tokenfield .token {
     border: 1px solid #5cb85c;
     background-color: #5cb85c;
     color:#eee;
 }
</style>
<div class="panel panel-primary">
    <div class="panel-heading">
        {{ _('Edit' )}}
    </div>
    <div class="panel-body" style="border-bottom:1px solid #f6e1e1;padding:10px 0;">
        <div class="row" style="margin:0;padding:0;">
            <form id="topic-put">
                {% from 'topic/_form.html' import edit %}
                {{ edit(form) }}
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/topic/panel.html
{% if g.user.is_authenticated %}
<ul class="list-group">
    {% if topic in current_user.following_topics %}
    <button type="button" class="btn btn-info btn-block topicfollow active" id="{{ topic.id }}">取消关注</button>
    {% else %}
    <button type="button" class="btn btn-info btn-block topicfollow" id="{{ topic.id }}">关注问题</button>
    {% endif %}
    {% if current_user.is_authenticated and current_user == topic.author %}
    <a class="btn btn-success btn-block" href="{{ url_for('topic.edit',topicId=topic.uid)}}">
        编辑问题
    </a>
    {%- endif %}
    {% if topic.id | is_collected %}
    <span class="btn btn-default btn-block">已收藏</span>
    {% else %}
    <span class="btn btn-default btn-block" data-toggle="modal" data-target="#sidecollect">收藏问题</span>
    <div class="modal fade" id="sidecollect" tabindex="-1" role="dialog" aria-labelledby="sidecollectLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="sidecollectLabel">收藏夹</h4>
                </div>
                {% if not current_user.collects.all() %}
                <div class="modal-body">
                    <a href="{{ url_for('mine.collect') }}" style="text-decoration:none">
                        <i class="icon icon-plus"></i> 创建
                    </a>
                </div>
                {% else %}
                <form action="{{ url_for('mine.collect_detail',topicId=topic.uid)}}" method="POST">
                    {{ form.hidden_tag() }}
                    <div class="modal-body">
                        <p> 添加到收藏夹 </p>
                        {% for collect in current_user.collects %}
                        <label data-id="{{ collect.id }}"><input name="add-to-collect" type="checkbox" value="{{ collect.id}}" />{{ collect.name }}</label>
                        {% if collect.is_privacy %}
                        <span class="label label-default">私密</span>
                        {% else %}
                        <span class="label label-default">公开</span>
                        {% endif %}
                        <br/>
                        {% endfor %}
                    </div>
                    <div class="modal-footer" style="padding-top:5px;padding-bottom:5px;">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <button type="submit" class="btn btn-primary">提交</button>
                    </div>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
    {% endif %}
</ul>
{% endif %}

templates/topic/replies.html
<style>
 .like-active {
     color:#a40004;
 }
 .like-no-active {
     color:#ccc;
 }
 .reply-order a{
     padding: 1px 2px;
     color: #778087;
     text-decoration: none;
     font-size:13px;
 }
 .reply-count {
     font-size:12px;
     color:#999;
 }
 .reply-content a {
     color:#778087;
 }
</style>
<div class="panel panel-default">
    <div class="panel-heading">
        {{ _('Received %(total)s replies',total=replies.total) }}
        <ul class="pull-right list-inline reply-order">
            <li><a href="{{ url_for('topic.topic',topicId=topic.uid,orderby='time')}}"> <i class="icon icon-time"></i>{{_('time')}}</a></li>
            <li><a href="{{ url_for('topic.topic',topicId=topic.uid,orderby='like')}}"> <i class="icon icon-thumbs-up"></i>{{_('likers')}}</a></li>
        </ul>
    </div>
    {% if replies.items %}
    {% set num = 1 %}
    {% for reply in replies.items %}
    <div class="panel-body media" id="reply-{{ reply.id }}" style="border-bottom:1px solid #eee;margin:0">
        <div class="media-left">
            <a href="{{ url_for('user.user',user_url=reply.author.username) }}">
                <img class="media-object img-circle" src="{{ link_base.avatar(reply.author)}}" alt="avatar" style="width:48px;height:48px">
            </a>
        </div>
        <div class="media-body">
            <small class="media-heading" style="color:#999">
                <span>{{ link_base.user(reply.author.username)}}</span>
                <span>{{ reply.publish | timesince }}</span>
                <a name="reply{{ reply.id }}" class="anchor" href="#reply{{ num }}" aria-hidden="true">#{{ num }}</a>
            </small>
            <div  class="reply-content">
                {{ reply.content | safe_clean }}
            </div>
        </div>
        <div class="media-right">
            {% if reply in current_user.likes and g.user.is_authenticated %}
            <a href="javascript:void(0);" style="padding:0" class="like-reply btn btn-sm like-active" data-id="{{ reply.id}}" title="取消赞">
                <i class="icon-thumbs-up"></i>
                <span class="reply-count">{{ reply.likers | length }}</span>
            </a>
            {% else %}
            <a href="javascript:void(0);" style="padding:0" class="like-reply btn btn-sm like-no-active" data-id="{{ reply.id}}" title="赞">
                <i class="icon-thumbs-up"></i>
                <span class="reply-count">{{ reply.likers | length }}</span>
            </a>
            {% endif %}
        </div>
        <div class="media-right">
            <a href="javascript:void(0);" style="color:#ccc;padding:0" class="reply-author btn btn-sm" data-id="{{ reply.author.username }}" title="回复">
                <i class="icon-reply"></i>
            </a>
        </div>
    </div>
    {% set num = num + 1 %}
    {% endfor %}
    {{ p_footer(replies,'topic.topic',dict(topicId=topic.uid))}}
    {% else %}
    <div class="panel-body">
        <span class="text-center" style="display:block;width:100%;color:#999">
            {{_('no reply')}}
        </span>
    </div>
    {% endif %}
</div>
<div class="panel panel-default">
    {% if g.user.is_authenticated %}
    <div class="panel-heading"> {{ _('Reply this topic') }} </div>
    <div class="panel-body">
        <form action="{{ url_for('topic.reply',topicId=topic.id)}}" method="POST">
            {{ form.hidden_tag() }}
            {{ form.content(class='form-control',rows=4)}}
            <button class="btn btn-sm btn-primary" type="submit" style="margin-top:10px;">{{ _('Post reply') }}</button>
        </form>
    </div>
    {% else %}
    <div class="panel-body" style="border:1px dashed #337ab7;margin:5px;">
        <span class="text-center" style="display:block;width:100%;color:#999">
            <span class="glyphicon glyphicon-lock" aria-hidden="true" style="font-size:16px;"></span>
            {{_('You need')}} <a href="{{ url_for('auth.login') }}">{{ _('Login')}}</a> {{_('before you can reply.')}}
        </span>
    </div>
    {% endif %}
</div>