maple/topic/urls.py
from flask import Blueprint
from .views import ask, good, preview, vote_up, vote_down, edit
from .views import TopicAPI, ReplyAPI

site = Blueprint('topic', __name__)

site.add_url_rule('/ask', view_func=ask)
site.add_url_rule('/good', view_func=good)
site.add_url_rule('/preview', view_func=preview, methods=['POST'])
site.add_url_rule('/up/<topicId>', view_func=vote_up, methods=['POST'])
site.add_url_rule('/down/<topicId>', view_func=vote_down, methods=['POST'])
site.add_url_rule('/edit/<topicId>', view_func=edit)

topic_view = TopicAPI.as_view('topic')
# /topic
# /topic         post
# /topic/<uid>   get,put,delete
site.add_url_rule('',
                  defaults={'topicId': None},
                  view_func=topic_view,
                  methods=['GET'])
site.add_url_rule('', view_func=TopicAPI.as_view('post'), methods=['POST'])
site.add_url_rule('/<topicId>',
                  view_func=topic_view,
                  methods=['GET', 'PUT', 'DELETE'])

reply_view = ReplyAPI.as_view('reply')
site.add_url_rule('reply/<topicId>', view_func=reply_view, methods=['POST'])

maple/urls.py
from maple.forums.urls import site as forums_site
from maple.topic.urls import site as topic_site
from maple.board.urls import site as board_site
from maple.user.urls import site as user_site
from maple.mine.urls import site as mine_site
from maple.setting.urls import site as setting_site
from maple.upload.urls import site as upload_site
from maple.tag.urls import site as tag_site
from maple.docs.views import site as docs_site


def register_urls(app):
    app.register_blueprint(forums_site)
    app.register_blueprint(board_site, url_prefix='/<parent_b>')
    app.register_blueprint(tag_site, url_prefix='/t')
    app.register_blueprint(topic_site, url_prefix='/topic')
    app.register_blueprint(mine_site, url_prefix='/user')
    app.register_blueprint(user_site, url_prefix='/u/<user_url>')
    app.register_blueprint(setting_site, url_prefix='/setting')
    app.register_blueprint(upload_site)
    app.register_blueprint(docs_site, subdomain='docs')
    from maple.auth import views
    from maple.admin import admin

maple/user/urls.py
from flask import Blueprint, abort, g
from maple.user.models import User
from maple.forums.forms import MessageForm
from .views import user, topic, reply, collect, following, follower,collect_detail

site = Blueprint('user', __name__)


@site.before_request
def before():
    g.message_form = MessageForm()


@site.url_value_preprocessor
def pull_user_url(endpoint, values):
    g.user_url = values.pop('user_url')
    user = User.query.filter_by(username=g.user_url).first()
    if user is None:
        abort(404)


@site.url_defaults
def add_user_url(endpoint, values):
    if 'user_url' in values or not g.user_url:
        return
    values['user_url'] = g.user_url


site.add_url_rule('', view_func=user)
site.add_url_rule('/topics', view_func=topic)
site.add_url_rule('/replies', view_func=reply)
site.add_url_rule('/collects', view_func=collect)
site.add_url_rule('/collects/<int:collectId>', view_func=collect_detail)
site.add_url_rule('/following', view_func=following)
site.add_url_rule('/followers', view_func=follower)

maple/topic/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Length
from flask_babelex import lazy_gettext as _
from maple.forums.models import Board


class TopicForm(Form):
    title = StringField(_('Title:'), [DataRequired(), Length(min=4, max=36)])
    content = TextAreaField(_('Content:'), [DataRequired(), Length(min=6)])
    category = SelectField(
        _('Category:'),
        choices=[(b.id, b.board + '   --' + b.parent_board)
                 for b in Board.query.all()],
        coerce=int)
    tags = StringField(_('Tags:'), [DataRequired(), Length(min=2, max=36)])
    choice = SelectField('choice',
                         choices=[(1, 'Markdown'), (2, 'Default')],
                         coerce=int)


class ReplyForm(Form):
    content = TextAreaField(_('Content:'), [DataRequired()])

maple/user/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField, SelectField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo
from flask_babelex import lazy_gettext as _


class ProfileForm(Form):
    introduce = TextAreaField('个人介绍:', [Length(min=4)])
    school = StringField('所在学校:', [Length(min=4, max=20)])
    word = TextAreaField('个性签名:', [Length(min=4)])


class PasswordForm(Form):
    password = PasswordField('原密码:', [DataRequired(), Length(min=4, max=20)])
    password_n = PasswordField('新密码:',
                               [DataRequired(), Length(min=4, max=20),
                                EqualTo('password_nn')])
    password_nn = PasswordField('重复新密码:', [DataRequired()])


choices = [(1, '所有人'), (2, '已登陆用户'), (3, '仅自己')]


class PrivacyForm(Form):
    online_status = SelectField('登录状态', coerce=int, choices=choices)
    topic_list = SelectField('主题列表', coerce=int, choices=choices)

    rep_list = SelectField('回复列表', coerce=int, choices=choices)
    ntb_list = SelectField('笔记列表', coerce=int, choices=choices)
    collect_list = SelectField('收藏列表', coerce=int, choices=choices)

maple/topic/views.py
from flask import (render_template, redirect, url_for, request, jsonify,
                   current_app)
from flask.views import MethodView
from flask_login import login_required
from flask_maple.forms import flash_errors, return_errors
from flask_babelex import gettext as _
from maple import db
from maple.helpers import replies_page
from maple.helpers import is_num
from maple.forums.models import Board
from maple.filters import safe_clean, Filters
from .models import Topic
from .forms import TopicForm, ReplyForm
from .controls import TopicModel, ReplyModel, vote
from .permission import (topic_permission, reply_permission, ask_permission,
                         vote_permission, preview_permission, edit_permission)


@login_required
@ask_permission
def ask():
    form = TopicForm()
    boardId = request.args.get('boardId')
    if boardId is not None:
        board = Board.query.filter_by(id=boardId).first()
        form.category.data = board.id

    data = {'title': '提问 - ', 'form': form}
    return render_template('topic/ask.html', **data)


@login_required
@edit_permission
def edit(topicId):
    topic = Topic.query.filter_by(uid=topicId).first_or_404()
    form = TopicForm()
    form.title.data = topic.title
    form.category.data = topic.board_id
    form.tags.data = ','.join([tag.tagname for tag in topic.tags])
    form.content.data = topic.content
    data = {'title': _('Edit -'), 'form': form, 'topic': topic}
    return render_template('topic/edit.html', **data)


def good():
    page = is_num(request.args.get('page'))
    topics = Topic.query.filter_by(is_good=True).paginate(
        page, current_app.config['PER_PAGE'],
        error_out=True)
    data = {'title': '精华文章 - ', 'topics': topics}
    return render_template('topic/topic_good.html', **data)


@login_required
@preview_permission
def preview():
    choice = request.values.get('choice')
    content = request.values.get('content')
    print(choice)
    if choice == '2':
        return safe_clean(content)
    else:
        return Filters.safe_markdown(content)


@vote_permission
def vote_up(topicId):
    topic = Topic.query.filter_by(uid=topicId).first_or_404()
    if not topic.vote:
        topic.vote = 1
    else:
        topic.vote += 1
    db.session.commit()
    html = vote(topic.vote)
    return jsonify(judge=True, html=html)


@vote_permission
def vote_down(topicId):
    topic = Topic.query.filter_by(uid=topicId).first_or_404()
    if not topic.vote:
        topic.vote = -1
    else:
        topic.vote -= 1
    db.session.commit()
    html = vote(topic.vote)
    return jsonify(judge=True, html=html)


class TopicAPI(MethodView):
    decorators = [topic_permission]

    def template_with_uid(self, data):
        return render_template('topic/content.html', **data)

    def template_without_uid(self, data):
        return render_template('topic/topic.html', **data)

    def get(self, topicId):
        page = is_num(request.args.get('page'))
        order = request.args.get('orderby')
        if topicId is None:
            topics, top_topics = TopicModel.get_list(page)
            data = {'title': '所有主题 - ',
                    'topics': topics,
                    'top_topics': top_topics}
            return self.template_without_uid(data)
        else:
            form = ReplyForm()
            topic, replies = TopicModel.get_detail(page, topicId, order)
            data = {'title': '%s - ' % topic.title,
                    'form': form,
                    'topic': topic,
                    'replies': replies}
            return self.template_with_uid(data)

    def post(self):
        form = TopicForm()
        if form.validate_on_submit():
            topic = TopicModel.post(form)
            return redirect(url_for('topic.topic', topicId=topic.uid))
        else:
            if form.errors:
                flash_errors(form)
            return redirect(url_for('topic.ask'))

    def put(self, topicId):
        form = TopicForm()
        if form.validate_on_submit():
            TopicModel.put(form, topicId)
            return jsonify(judge=True)
        else:
            if form.errors:
                return_errors(form)
            return redirect(url_for('topic.ask'))

    def delete(self, topicId):
        return 'delete'


class ReplyAPI(MethodView):
    decorators = [reply_permission]

    def post(self, topicId):
        form = ReplyForm()
        topic = Topic.query.filter_by(id=topicId).first_or_404()
        if form.validate_on_submit():
            rep = ReplyModel()
            reply = rep.post(form, topicId)
            page = replies_page(topic.id)
            return redirect(url_for('topic.topic',
                                    topicId=topic.uid,
                                    page=page,
                                    _anchor='reply' + str(reply.id)))
        else:
            if form.errors:
                flash_errors(form)
            page = replies_page(topic.id)
            return redirect(url_for('topic.topic',
                                    topicId=topic.uid,
                                    page=page,
                                    _anchor='content'))

    # def put(self, uid):
    #     return 'put'

    # def delete(self, uid):
    #     return 'delete'

maple/user/views.py
from flask import (render_template, request, g, url_for, redirect, abort,
                   current_app)
from flask_login import current_user
from maple.helpers import is_num
from maple.topic.models import Topic, Reply, Collect, Like
from maple.user.models import User
from sqlalchemy.sql import func


def user():
    topics = Topic.query.join(Topic.author).filter(
        User.username == g.user_url).paginate(1,
                                              current_app.config['PER_PAGE'],
                                              error_out=True)
    data = {'type': 'topic', 'topics': topics}
    return render_template('user/user.html', **data)


def topic():
    orderby = request.args.get('orderby')
    page = is_num(request.args.get('page'))
    all_order = ['vote', 'publish']
    if orderby and orderby not in all_order:
        abort(404)
    if orderby == 'vote':
        topics = Topic.query.join(Topic.author).filter(
            User.username == g.user_url).order_by(Topic.vote.desc()).paginate(
                page, current_app.config['PER_PAGE'],
                error_out=True)
    else:
        topics = Topic.query.join(Topic.author).filter(
            User.username == g.user_url).paginate(
                page, current_app.config['PER_PAGE'],
                error_out=True)
    data = {'type': 'topic', 'topics': topics}
    return render_template('user/user.html', **data)


def reply():
    order = request.args.get('orderby')
    page = is_num(request.args.get('page'))
    all_order = ['like', 'publish']
    if order and order not in all_order:
        abort(404)
    if order == 'like':
        user = User.query.filter_by(username=g.user_url).first_or_404()
        replies = Reply.query.outerjoin(Like).filter(
            Reply.author_id == user.id).group_by(Reply.id).order_by(func.count(
                Like.id).desc()).paginate(page, current_app.config['PER_PAGE'],
                                          True)
    else:
        replies = Reply.query.join(Reply.author).filter(
            User.username == g.user_url).paginate(
                page, current_app.config['PER_PAGE'],
                error_out=True)
    data = {'type': 'reply', 'replies': replies}
    return render_template('user/user.html', **data)


def collect():
    page = is_num(request.args.get('page'))
    per_page = current_app.config['PER_PAGE']
    if current_user.is_authenticated and current_user.username == g.user_url:
        collects = current_user.collects.paginate(
            page, per_page, error_out=True)
    else:
        collects = Collect.query.join(Collect.author).filter(
            Collect.is_privacy == False, User.username == g.user_url).paginate(
                page, per_page, error_out=True)
    data = {'type': 'collect', 'collects': collects}
    return render_template('user/user.html', **data)


def collect_detail(collectId):
    page = is_num(request.args.get('page'))
    per_page = current_app.config['PER_PAGE']
    if current_user.is_authenticated:
        collect = Collect.query.join(Collect.author).filter(
            Collect.id == collectId,
            User.username == g.user_url).first_or_404()
    else:
        collect = Collect.query.join(Collect.author).filter(
            Collect.id == collectId, Collect.is_privacy == False,
            User.username == g.user_url).first_or_404()
    topics = collect.topics.paginate(page, per_page, True)
    data = {'type': 'collect_detail', 'topics': topics, 'collect': collect}
    return render_template('user/user.html', **data)


def following():
    return redirect(url_for('mine.follow'))


def follower():
    page = is_num(request.args.get('page'))
    order = request.args.get('orderby')
    order_list = ['publish', 'score']
    if order and order not in order_list:
        abort(404)
    user = User.query.filter_by(username=g.user_url).first_or_404()
    followers = user.followers.paginate(page,
                                        current_app.config['PER_PAGE'],
                                        error_out=True)
    data = {'type': 'follower', 'followers': followers}
    return render_template('user/user.html', **data)

templates/user/collect.html
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <div class="col-md-8">
            收藏夹名
        </div>
        <div class="col-md-4">
            收藏数
        </div>
    </div>
    {% if collects.items %}
    {% if setting.collect_list == 1 or (setting.collect_list == 2 and g.user.is_authenticated) or (g.user.is_authenticated and g.user.username == g.user_url) %}
    {% for collect in collects.items %}
    <div class="panel-body" style="border-bottom:1px solid #eee">
        <div class="row" style="margin:0">
            <div class="col-md-8">
                <a href="{{ url_for('user.collect_detail',collectId =collect.id)}}">{{ collect.name }}</a>
            </div>
            <div class="col-md-4">
                {% if g.user.is_authenticated -%}
                <span class="pull-right">
                    {% if collect in current_user.following_collects -%}
                    <button class="btn btn-sm btn-default collectfollow active" id="{{ collect.id}}" style="padding:0 5px">取消关注</button>
                    {%- else %}
                    <button class="btn btn-sm btn-default collectfollow" id="{{ collect.id}}" style="padding:0 5px">关注</button>
                    {%- endif %}
                </span>
                {%- endif %}
                <span style="margin-left:20px">
                    {{ collect.topics.count() }}
                </span>
            </div>
        </div>
    </div>
    {% endfor  %}
    {{ p_footer(collects,'user.collect')}}
    {% else %}
    <div class="panel-body" style="border:1px dashed #337ab7;margin:5px;">
        <span class="text-center" style="display:block;width:100%;color:#999">
            <span class="glyphicon glyphicon-lock" aria-hidden="true" style="font-size:16px;"></span>
            {{_("Due to user's setting,the list have been hidden.")}}
        </span>
    </div>
    {% endif %}
    {% else %}
    <div class="panel-body text-center">
        {{_('No Collect')}}
    </div>
    {% endif %}
</div>

templates/user/collect_detail.html
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <h3><strong>{{ collect.name }}</strong></h3>
    </div>
    {% if topics.items %}
    {% if setting.collect_list == 1 or (setting.collect_list == 2 and g.user.is_authenticated) or (g.user.is_authenticated and g.user.username == g.user_url) %}
    {% for topic in topics.items %}
    <div class="panel-body" style="border-bottom:1px solid #eee">
        {{ link_base.topic(topic) }}
    </div>
    {% endfor  %}
    {{ p_footer(topics,'user.collect_detail')}}
    {% else %}
    <div class="panel-body" style="border:1px dashed #337ab7;margin:5px;">
        <span class="text-center" style="display:block;width:100%;color:#999">
            <span class="glyphicon glyphicon-lock" aria-hidden="true" style="font-size:16px;"></span>
            根据用户设置,列表被隐藏
        </span>
    </div>
    {% endif %}
    {% else %}
    <div class="panel-body text-center">
        没有收藏
    </div>
    {% endif %}
</div>

templates/user/follower.html
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <span class="pull-right">
            {{_('Sort:')}}
            <div class="btn-group btn-group-xs" role="group">
                {% if request.args.get('orderby') == 'score' %}
                <a href="{{ url_for('user.follower',orderby='publish')}}" class="btn btn-default">{{_('time')}}</a>
                <a href="{{ url_for('user.follower',orderby='score')}}" class="btn btn-default active">{{_('score')}}</a>
                {% else %}
                <a href="" class="btn btn-default">{{_('time')}}</a>
                <a href="{{ url_for('user.follower',orderby='score')}}" class="btn btn-default active">{{_('score')}}</a>
                {% endif %}
            </div>
        </span>
    </div>
    {% if followers.items -%}
    {% for follower in followers.items %}
    <div class="panel-body" style="border-bottom:1px solid #eee">
        {{ link_base.user(follower.username) }}
    </div>
    {% endfor  %}
    {{ p_footer(followers,'user.follower')}}
    {% else %}
    <div class="panel-body text-center">
    {{_('No Follower')}}
    </div>
    {%- endif %}
</div>

templates/user/infor.html
{% macro other(user) -%}
{% if g.user.is_authenticated and current_user.username != g.user_url %}
<div class="list-group-item">
    <span class="text-right" style="display:block">
        {% if user in current_user.following_users %}
        <button class="btn btn-sm btn-default userfollow active" id="{{ user.id}}">取消关注</button>
        {% else %}
        <button class="btn btn-sm btn-default userfollow" id="{{ user.id}}">关注他</button>
        {% endif %}
        <button class="btn btn-sm btn-default" id="{{ user.id}}" title="私信" data-toggle="modal" data-target="#send-message"><i class="icon-comments-alt" style="font-size:16px;"></i></button>
    </span>
</div>
{% endif %}
{%- endmacro %}

{% macro mine(user) -%}
{% if g.user.is_authenticated and current_user.username == g.user_url and not user.is_confirmed %}
<div class="alert alert-info" style="padding:6px;font-size:12px;margin-top:10px;">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ _("You haven't confirm your account,Please confirmed") }}
    <span id="email-confirm" class="btn btn-info btn-sm" style="padding:2px 5px;">{{ _('Activate  Account')}}</span>
</div>
{% endif %}
{%- endmacro %}

<div class="list-group">
    <div class="media list-group-item">
        <div class="media-left">
            <img class="media-object img-circle" src="{{ link_base.avatar(user) }}" alt="avatar" style="width:64px;height:64px">
        </div>
        <div class="media-body">
            <h4 class="media-heading">
                {{ user.username}}
                {%- set _a = (setting.online_status == 1 and user.username | is_online) %}
                {%- set _b = (setting.online_status == 2 and current_user.is_authenticated and user.username | is_online) %}
                {%- if _a or _b %}
                <span class="online">{{ _('ONLINE') }} </span>
                {%- else %}
                <span class="online">{{ _('OUTLINE') }}</span>
                {% endif -%}
            </h4>
            <small style="color:#999">
                <span>第{{ user.id }}号会员</span>/
                <span>{{user.register_time | timesince }}</span>
                <br/>
                <span>{{ user.topics.count() }}篇主题</span> |
                <span>{{ user.replies.count() }}条回复</span>
            </small>
        </div>
        <blockquote style="font-size:14px;">
            <p>{{ user.infor.word }}</p>
            <footer>Someone famous in <cite title="Source Title">{{ user.infor.school }}</cite></footer>
        </blockquote>
        <table  style="font-size:12px;width:100%" align="center">
            <tr>
                <td align="center" style="border-right:1px solid #AACCEE;"><p>1</p>积分</td>
                <td align="center" style="border-right:1px solid #AACCEE;"><p>{{ user.followers.count()}}</p>粉丝</td>
                <td align="center"><p>{{ user.following_users.count() }}</p>关注</td>
            </tr>
        </table>
    </div>
    {{ other(user) }}
    {{ mine(user) }}
</div>
<div class="modal fade" id="send-message" tabindex="-1" role="dialog" aria-labelledby="send-messageLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h5 class="modal-title" id="send-messageLabel">发送私信</h5>
            </div>
            <form action="{{ url_for('forums.message',receId=user.id)}}" method="POST">
                <div class="modal-body">
                    {{ g.message_form.hidden_tag() }}
                    {{ g.message_form.message(class="form-control",placeholder="仅支持纯文本,不超过1024字") }}
                </div>
                <div class="modal-footer" style="padding-top:5px;padding-bottom:5px;">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="submit" class="btn btn-primary">确认</button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/user/reply.html
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <span style="float:right">
            {{_("Sort:")}}
            <div class="btn-group btn-group-xs" role="group">
                {% if request.args.get('orderby') == 'like' %}
                <a href="{{ url_for('user.reply',orderby='publish')}}" class="btn btn-default">{{_('time')}}</a>
                <a href="{{ url_for('user.reply',orderby='like')}}" class="btn btn-default active">{{_('likers')}}</a>
                {% else %}
                <a href="" class="btn btn-default active">{{_('time')}}</a>
                <a href="{{ url_for('user.reply',orderby='like')}}" class="btn btn-default">{{_('likers')}}</a>
                {% endif %}
            </div>
        </span>
    </div>
    {% if replies.items %}
    {% if setting.rep_list == 1 or (g.user.is_authenticated and setting.rep_list == 2) or (g.user.is_authenticated and g.user.username == g.user_url) %}
    {% for reply in replies.items %}
    <div class="panel-body" style="border-bottom:1px solid #eee">
        <span style="font-size:12px;color:#999;">
            {{_('replied %(title)s created by %(author)s',title=link_base.topic(reply.topic),author = link_base.user(reply.author))}}
        </span>
        <p>{{ reply.content | safe_clean }}</p>
        <span style="font-size:12px;color:#999;">
            {{_('replied time:')}}{{ reply.publish | timesince }}
        </span>
    </div>
    {% endfor  %}
    {{ p_footer(replies,'user.reply')}}
    {% else %}
    <div class="panel-body" style="border:1px dashed #337ab7;margin:5px;">
        <span class="text-center" style="display:block;width:100%;color:#999">
            <span class="glyphicon glyphicon-lock" aria-hidden="true" style="font-size:16px;"></span>
            {{_("Due to user's setting,the list have been hidden.")}}
        </span>
    </div>
    {% endif %}
    {% else %}
    <div class="panel-body text-center">
        {{_('No Reply')}}
    </div>
    {% endif %}
</div>

templates/user/topic.html
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <span style="float:right">
            {{_('Sort:')}}
            <div class="btn-group btn-group-xs" role="group">
                {% if request.args.get('orderby') == 'vote' %}
                <a href="{{ url_for('user.topic',orderby='publish')}}" class="btn btn-default">{{_('time')}}</a>
                <a href="{{ url_for('user.topic',orderby='vote')}}" class="btn btn-default active">{{_('vote')}}</a>
                {% else %}
                <a href="" class="btn btn-default active">{{_('time')}}</a>
                <a href="{{ url_for('user.topic',orderby='vote')}}" class="btn btn-default">{{_('vote')}}</a>
                {% endif %}
            </div>
        </span>
    </div>
    {% if topics.items %}
    {% if setting.topic_list == 1 or (setting.topic_list == 2 and g.user.is_authenticated) or (g.user.is_authenticated and g.user.username == g.user_url) %}
    {% for topic in topics.items %}
    <div class="panel-body" style="border-bottom:1px solid #eee;font-size:16px;">
        <span style="color:#666">{{ topic.board.board }}</span>
        {{ link_base.topic(topic) }}
        <div style="font-size:12px;color:#999;">
            {{_('create time:')}}{{ topic.publish | timesince }}
            · {{ _('the last reply published by %(author)s',author=link_base.user(topic.author.username))}}
        </div>
    </div>
    {% endfor  %}
    {{ p_footer(topics,'user.topic')}}
    {% else %}
    <div class="panel-body" style="border:1px dashed #337ab7;margin:5px;">
        <span class="text-center" style="display:block;width:100%;color:#999">
            <span class="glyphicon glyphicon-lock" aria-hidden="true" style="font-size:16px;"></span>
            {{_("Due to user's setting,the list have been hidden.")}}
        </span>
    </div>
    {% endif %}
    {% else %}
    <div class="panel-body text-center">
        {{_('No Topic')}}
    </div>
    {% endif %}
</div>

templates/user/user.html
{% extends 'base/base.html' %}
{% block content %}
<script type="text/javascript">
 $(document).ready(function(){
     var urlType = '{{type}}';
     if (urlType == 'topic'){
         $('li.topics').addClass('active');
     }else if(urlType == 'reply') {
         $('li.replies').addClass('active');
     }else if(urlType == 'collect') {
         $('li.collects').addClass('active');
     }else if(urlType == 'collect_detail') {
         $('li.collects').addClass('active');
     }else if(urlType == 'notebook') {
         $('li.notebooks').addClass('active');
     }else if(urlType == 'follower') {
         $('li.followers').addClass('active');
     }
 });
</script>
{% import 'base/link.html' as link_base %}
{% from 'base/paginate.html' import footer as p_footer %}
{{ breadcrumb(active=g.user_url)}}
<div class="row">
    <div class="col-md-3" style="padding-right:0;">
        {% set user = g.user_url | get_user_infor %}
        {% set setting = user.setting %}
        {% include 'user/infor.html' %}
        <div  style="background:#fff;border:1px solid #ddd;border-radius:5px">
            {% if g.user.is_authenticated and current_user.username == g.user_url %}
            {{ nav_list(_('me'))}}
            {% else %}
            {{ nav_list(g.user_url)}}
            {% endif %}
        </div>
    </div>
    <div class="col-md-9">
        {% include "user/" + type + ".html" %}
    </div>
</div>
{% endblock %}

{% macro nav_list(name) -%}
<ul class="nav nav-pills nav-stacked" >
    <li role="presentation" class="topics"><a href="{{ url_for('user.topic')}}">{{ _("topics of %(n)s",n = name) }}</a></li>
    <li role="presentation" class="replies"><a href="{{ url_for('user.reply')}}">{{ _("replies of %(n)s",n = name) }}</a></li>
    <li role="presentation" class="collects"><a href="{{ url_for('user.collect')}}">{{ _("collects of %(n)s",n = name) }}</a></li>
    <li role="presentation" class="followers"><a href="{{ url_for('user.follower')}}">{{ _("followers of %(n)s",n = name) }}</a></li>
</ul>
{%- endmacro %}