maple/forums/urls.py
from flask import Blueprint
from flask_login import login_required
from .views import (index, forums, notice, userlist, message, about, help,
                    order, contact)

site = Blueprint('forums', __name__)

notice = login_required(notice)
userlist = login_required(userlist)
message = login_required(message)

site.add_url_rule('/', view_func=index)
site.add_url_rule('/index', view_func=forums)
site.add_url_rule('/notices', view_func=notice)
site.add_url_rule('/userlist', view_func=userlist)
site.add_url_rule('/about', view_func=about)
site.add_url_rule('/help', view_func=help)
site.add_url_rule('/contact', view_func=contact)
site.add_url_rule('/order', view_func=order, methods=['POST'])
site.add_url_rule('/messages/<receId>', view_func=message, methods=['POST'])

maple/urls.py
from maple.forums.urls import site as forums_site
from maple.topic.urls import site as topic_site
from maple.board.urls import site as board_site
from maple.user.urls import site as user_site
from maple.mine.urls import site as mine_site
from maple.setting.urls import site as setting_site
from maple.upload.urls import site as upload_site
from maple.tag.urls import site as tag_site
from maple.docs.views import site as docs_site


def register_urls(app):
    app.register_blueprint(forums_site)
    app.register_blueprint(board_site, url_prefix='/<parent_b>')
    app.register_blueprint(tag_site, url_prefix='/t')
    app.register_blueprint(topic_site, url_prefix='/topic')
    app.register_blueprint(mine_site, url_prefix='/user')
    app.register_blueprint(user_site, url_prefix='/u/<user_url>')
    app.register_blueprint(setting_site, url_prefix='/setting')
    app.register_blueprint(upload_site)
    app.register_blueprint(docs_site, subdomain='docs')
    from maple.auth import views
    from maple.admin import admin

maple/forums/models.py
from maple import db
from datetime import datetime
from sqlalchemy.dialects.postgresql import JSON


class Board(db.Model):
    __tablename__ = 'boards'
    id = db.Column(db.Integer, primary_key=True)
    rank = db.Column(db.Integer, default=1)
    board = db.Column(db.String(81), nullable=False)
    parent_board = db.Column(db.String(81), nullable=False)
    description = db.Column(db.Text(), nullable=False)

    count_id = db.Column(db.Integer,
                         db.ForeignKey('counts.id',
                                       ondelete="CASCADE"))
    count = db.relationship('Count',
                            backref="board",
                            cascade='all,delete-orphan',
                            single_parent=True,
                            uselist=False)

    __mapper_args__ = {"order_by": rank.desc()}

    def __str__(self):
        return self.board

    def __repr__(self):
        return '<Board %r>' % self.board


class Count(db.Model):
    __tablename__ = 'counts'
    id = db.Column(db.Integer, primary_key=True)
    drafts = db.Column(db.Integer, default=0)
    collects = db.Column(db.Integer, default=0)
    inviteds = db.Column(db.Integer, default=0)
    follows = db.Column(db.Integer, default=0)
    topics = db.Column(db.Integer, default=0)
    all_topics = db.Column(db.Integer, default=0)

    def __repr__(self):
        return '<Count %r>' % self.id


class Notice(db.Model):
    __tablename__ = 'notices'
    id = db.Column(db.Integer, primary_key=True)
    publish = db.Column(db.DateTime, default=datetime.now())
    category = db.Column(db.String(81), nullable=False)
    content = db.Column(JSON)
    is_read = db.Column(db.Boolean, default=False)

    rece_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    rece_user = db.relationship("User",
                                backref="rece_user",
                                foreign_keys='Notice.rece_id',
                                uselist=False)

    send_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    send_user = db.relationship("User",
                                backref="send_user",
                                foreign_keys='Notice.send_id',
                                uselist=False)

    def __repr__(self):
        return '<Notice %r>' % self.id

maple/forums/forms.py
from flask_wtf import Form
from wtforms import SelectField, StringField, TextAreaField
from wtforms.validators import DataRequired
from flask_babelex import lazy_gettext as _


class SortForm(Form):
    display = SelectField(
        _('Choice'),
        coerce=int,
        choices=[(0, _('All Topics')), (1, _('One Day')), (2, _('One Week')), (
            3, _('One Month'))])
    sort = SelectField('Sort',
                       coerce=int,
                       choices=[(0, _('Publish')), (1, _('Author'))])
    st = SelectField('Up and Down',
                     coerce=int,
                     choices=[(0, _('Desc')), (1, _('Asc'))])


class SearchForm(Form):
    search = StringField(_('search'), validators=[DataRequired()])


class MessageForm(Form):
    message = TextAreaField(_('message'), validators=[DataRequired()])

maple/docs/views.py
from flask import Blueprint, render_template, send_from_directory
from os import path as ph

site = Blueprint('docs',
                 __name__,
                 template_folder='templates',
                 static_folder='static')


@site.route('/')
def docs():
    return render_template('docs/doc_list.html')


@site.route('/flask-maple/<path:path>')
def flask_maple(path):
    return send_from_directory(
        ph.join(site.static_folder, 'flask-maple'), path)


@site.route('/flask-avatar/<path:path>')
def flask_avatar(path):
    return send_from_directory(
        ph.join(site.static_folder, 'flask-avatar'), path)

maple/forums/views.py
from flask import (render_template, g, request, abort, redirect, flash,
                   url_for, current_app)
from flask_login import current_user
from flask_babelex import gettext as _
from flask_maple.forms import flash_errors
from maple.helpers import is_num
from maple.user.models import User
from maple.forums.models import Notice, Board
from maple.topic.models import Topic
from .forms import MessageForm
from maple import cache, db


def index():
    topics = Topic.query.filter_by(is_good=True, is_top=False).paginate(1, 10)
    top_topics = Topic.query.filter_by(is_top=True).limit(5)
    if not topics.items:
        topics = Topic.query.filter_by(is_top=False).paginate(1, 10)
    data = {'title': '', 'topics': topics, 'top_topics': top_topics}
    return render_template('forums/index.html', **data)


def forums():
    boards = {}
    parent_boards = db.session.query(Board.parent_board).group_by(
        Board.parent_board)
    for parent_board in parent_boards:
        child_board = Board.query.filter_by(parent_board=parent_board).all()
        boards[parent_board[0]] = child_board
    data = {'title': _('Index - '), 'boards': boards}
    return render_template('forums/forums.html', **data)


@cache.cached(timeout=60)
def notice():
    page = is_num(request.args.get('page'))
    notices = Notice.query.filter_by(
        rece_id=current_user.id).order_by(Notice.publish.desc()).paginate(
            page, current_app.config['PER_PAGE'],
            error_out=True)
    unread_notices = Notice.query.filter_by(rece_id=current_user.id,
                                            is_read=False).all()
    if unread_notices:
        for notice in unread_notices:
            notice.is_read = True
        db.session.commit()
    data = {'title': _('Notice - '), 'notices': notices}
    return render_template('forums/notice.html', **data)


def userlist():
    page = is_num(request.args.get('page'))
    users = User.query.paginate(page,
                                current_app.config['PER_PAGE'],
                                error_out=True)
    data = {'title': _('Userlist - '), 'users': users}
    return render_template('forums/userlist.html', **data)


def message(receId):
    form = MessageForm()
    rece_user = User.query.filter_by(id=receId).first_or_404()
    if form.validate_on_submit() and request.method == "POST":
        message = Notice()
        message.category = 'privacy'
        message.content = {'content': form.message.data}
        message.rece_user = rece_user
        message.send_id = current_user.id
        db.session.add(message)
        db.session.commit()
        flash(_('send succeccfully'), category='success')
        return redirect(url_for('user.user', user_url=rece_user.username))
    else:
        if form.errors:
            flash_errors(form)
    return redirect(url_for('user.user', user_url=rece_user.username))


@cache.cached(timeout=60)
def about():
    data = {'title': _('About - ')}
    return render_template('forums/about.html', **data)


@cache.cached(timeout=60)
def help():
    data = {'title': _('Help - ')}
    return render_template('forums/help.html', **data)


@cache.cached(timeout=60)
def contact():
    data = {'title': _('Contact - ')}
    return render_template('forums/contact.html', **data)


def order():
    from maple.main.orderby import form_judge
    form = g.sort_form
    if form.validate_on_submit():
        topics = form_judge(form)
        data = {'topics': topics}
        return render_template('base/sort.html', **data)
    else:
        abort(404)

templates/forums/about.html
{% extends 'base/base.html' %}
{% block content %}
{{ breadcrumb(active=_('About')) }}
{% cache 300 %}
<div class="panel panel-primary">
    <div class="panel-heading">
        {{ _('About')}}
    </div>
    <div class="panel-body">
        This is a platform in which we can propagate our activities.
    </div>
</div>
{% endcache %}
{% endblock %}

templates/forums/contact.html
{% extends 'base/base.html' %}
{% block content %}
{{ breadcrumb(active=_('Contact me')) }}
{% cache 300 %}
<div class="panel panel-primary">
    <div class="panel-heading">
        {{ _('Contact me') }}
    </div>
    <div class="panel-body">
          code_future@163.com
    </div>
</div>
{% endcache %}
{% endblock %}

templates/forums/forums.html
{% extends 'base/base.html' %}
{% block content %}
{{ breadcrumb(active=_('Board'))}}
{% for parent_board,child_boards in boards.items() %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <a href="{{ url_for('board.board',parent_b=parent_board)}}" style="color:#fff"> {{ parent_board }} </a>
    </div>
    {% from 'board/board_base.html' import body as board_body %}
    {{ board_body(child_boards)}}
</div>
{% endfor %}
{% endblock %}

templates/forums/help.html
{% extends 'base/base.html' %}
{% block content %}
{{ breadcrumb(active=_('Help')) }}
{% cache 300 %}
<div class="panel panel-primary">
    <div class="panel-heading">
        {{ _('Help') }}
    </div>
    <div class="panel-body">
        You have any question, please send an email to 'code_future@163.com'
    </div>
</div>
{% endcache %}
{% endblock %}

templates/forums/index.html
{% extends 'base/base.html' %}
{% block content %}
{{ breadcrumb() }}
{% cache 60 %}
{{ index_title() }}
{#<div class="row hidden-sm hidden-xs">#}
{#    {{ item(_('Forums'),url_for('forums.forums'),"icon-comments","#F86334")}}#}
{#    {{ item(_('Wiki'),url_for('docs.docs'),"icon-book","#eeccaa")}}#}
{#    {{ item(_('Blog'),'#',"icon-tasks")}}#}
{#    {{ item(_('Good'),url_for('topic.good'),"icon-globe","#017e66")}}#}
{#</div>#}
{% endcache %}
<div class="row">
    <div class="col-md-9">
        <div class="panel panel-default">
            {% from 'topic/topic_list.html' import view_no_form as board_view %}
            {{ board_view(topics,top_topics)}}
            <div class="panel-footer clearfix">
                <a class="pull-right" href="{{ url_for('topic.good')}}">
                    {{ _('more good topics') }}
                    <i class="icon-arrow-right"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-3" style="padding-left:0">
        {{ panel_base.index() }}
    </div>
</div>
{% endblock %}
{% macro index_title() -%}

{#<div class="panel panel-default hidden-xs">#}
{#    <div class="panel-body" style="text-align: center;">#}
{#        <div class="media" style="width: 480px; margin:0px auto; text-align: left;">#}
{#            <div class="media-left">#}
{#                <i class="icon-gift media-object" style="font-size: 55px; width: 55px; color: #333;"></i>#}
{#            </div>#}
{#            <div class="media-body" style="line-height: 200%; text-align: center;">#}
{#                <div style="font-size: 15px">#}
{#                    Honmaple {{ _('Office Source Code')}} <a href="https://github.com/honmaple/maple-bbs" target="_blank">Honmaple</a>#}
{#                </div>#}
{#                <div>#}
{#                    <code style="padding: 4px 10px;">git clone git@github.com:honmaple/maple-bbs.git</code>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}


{#<div class="panel panel-default hidden-xs">#}
{#    <div class="panel-body" style="text-align: center;">#}
{#        <div class="media" style="margin:0px auto; text-align: center;">#}
{#            <img src="/static/images/view3.jpg" style="height: 250px; width: 100%">#}
{#        </div>#}
{#    </div>#}
{#</div>#}

<div id="myCarousel" class="carousel slide">
    <!-- 轮播（Carousel）指标 -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>
    <!-- 轮播（Carousel）项目 -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="panel-body" style="text-align: center;">
                <div class="media" style="margin:0px auto; text-align: center;">
                    <img src="/static/images/Tsinghua/change1.jpg" style="height: 300px; width: 100%">
                </div>
            </div>
        </div>
        <div class="item">
            <div class="panel-body" style="text-align: center;">
                <div class="media" style="margin:0px auto; text-align: center;">
                     <img src="/static/images/Tsinghua/change2.jpg" style="height: 300px; width: 100%">
                </div>
            </div>
        </div>
        <div class="item">
            <div class="panel-body" style="text-align: center;">
                <div class="media" style="margin:0px auto; text-align: center;">
                    <img src="/static/images/Tsinghua/change3.jpg" style="height: 300px; width: 100%">
                </div>
            </div>
        </div>
        <div class="item">
            <div class="panel-body" style="text-align: center;">
                <div class="media" style="margin:0px auto; text-align: center;">
                    <img src="/static/images/Tsinghua/change4.jpg" style="height: 300px; width: 100%">
                </div>
            </div>
        </div>
        <div class="item">
            <div class="panel-body" style="text-align: center;">
                <div class="media" style="margin:0px auto; text-align: center;">
                    <img src="/static/images/Tsinghua/change5.jpg" style="height: 300px; width: 100%">
                </div>
            </div>
        </div>
    </div>
    <!-- 轮播（Carousel）导航 -->
    <a class="carousel-control left" href="#myCarousel"
       data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel"
       data-slide="next">&rsaquo;</a>

</div>
<script type="text/javascript">
$('#myCarousel').carousel({
	interval: 5000
})
</script>

{%- endmacro %}

{% macro item(name,url,icon,color="#337ab7") %}
<div class="col-md-3">
    <div class="panel panel-default">
        <a href="{{ url }}">
            <div class="panel-body text-center">
                <i class="{{ icon }}" style="font-size:55px;color:{{ color }}"></i>
            </div>
        </a>
        <a href="{{ url }}">
            <div class="panel-footer">
                {{ name }}
                <i class="pull-right icon-arrow-right"></i>
            </div>
        </a>
    </div>
</div>
{%- endmacro %}

templates/forums/notice.html
{% extends 'base/base.html' %}
{% block content %}
{{ breadcrumb(active=_('Notices'))}}
<div class="row">
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <button class="pull-right btn btn-sm btn-default ingore-all" style="padding:0 5px">{{ _('mark all to is read')}}</button>
                {{ _('Notices') }}
            </div>
            {% if notices.items %}
            {% for notice in notices.items %}
            <div class="panel-body" style="border-bottom:1px solid #eee;">
                {% import 'base/notice.html' as notice_base %}
                {{ notice_base[notice.category](notice) }}
            </div>
            {% endfor %}
            {{ p_footer(notices, 'forums.notice')}}
            {% else %}
            <div class="panel-body">
                <span class="text-center" style="display:block;width:100%;color:#999">
                    {{ _('No Notices')}}
                </span>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="col-md-3" style="padding-left:0">
        {{ panel_base.index() }}
    </div>
</div>
{% endblock %}

templates/forums/userlist.html
{% extends 'base/base.html' %}
{% block content %}
{{ breadcrumb(active=_('Userlist'))}}
<div class="row">
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                {{ _('Userlist')}}
            </div>
            {% for user in users.items %}
            <div class="panel-body" style="border-bottom:1px solid #eee">
                {{ link_base.user(user)}}
            </div>
            {% endfor %}
            {{ p_footer(users, 'forums.userlist')}}
        </div>
    </div>
    <div class="col-md-3"  style="padding-left:0">
        {{ panel_base.index() }}
    </div>
</div>
{% endblock %}